name: eco_ocean_game

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: "3.16.7"

dependencies:
  flame: ^1.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
