name: eco_ocean

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: "3.16.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.5.8
  flutter_test:
    sdk: flutter
  leancode_lint: ^8.0.0
  melos: ^4.0.0
