name: eco_ocean_l10n

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: "3.16.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
